FROM ghcr.io/cirruslabs/flutter:stable AS flutter-build

WORKDIR /app

COPY frontend_flutter/pubspec.yaml frontend_flutter/pubspec.lock ./
RUN flutter pub get

COPY frontend_flutter/ ./
RUN flutter build web --release

FROM nginx:1.27-alpine

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=flutter-build /app/build/web /usr/share/nginx/html

EXPOSE 80
