server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  gzip on;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;

  # Evitar el almacenamiento en caché de archivos de control y bootstrap de Flutter
  location ~* (index\.html|flutter_service_worker\.js|flutter_bootstrap\.js|manifest\.json|version\.json)$ {
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    expires -1;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|webp|woff|woff2|ttf|json|wasm|bin|map)$ {
    try_files $uri =404;
    expires 7d;
    add_header Cache-Control "public, immutable";
  }

  location /assets/ {
    try_files $uri =404;
    expires 7d;
    add_header Cache-Control "public, immutable";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
